--- 
distribution_type: module
generated_by: Module::Install version 0.67
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Postscript-HTML-Map
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Element: 0
  Math::Bezier: 0
version: 1.0
